//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoTagsSynchronizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFolder {
            get {
                return ((string)(this["LastFolder"]));
            }
            set {
                this["LastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1173, 778")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("283")]
        public int SplitContainerFolder {
            get {
                return ((int)(this["SplitContainerFolder"]));
            }
            set {
                this["SplitContainerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("549")]
        public int SplitContainerImages {
            get {
                return ((int)(this["SplitContainerImages"]));
            }
            set {
                this["SplitContainerImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("514")]
        public int SplitContainerMain {
            get {
                return ((int)(this["SplitContainerMain"]));
            }
            set {
                this["SplitContainerMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("277")]
        public int SplitContainerMap {
            get {
                return ((int)(this["SplitContainerMap"]));
            }
            set {
                this["SplitContainerMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastGoogleLocationFolder {
            get {
                return ((string)(this["LastGoogleLocationFolder"]));
            }
            set {
                this["LastGoogleLocationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LocationUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LocationUsers"]));
            }
            set {
                this["LocationUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocationUser {
            get {
                return ((string)(this["LocationUser"]));
            }
            set {
                this["LocationUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMainFormMaximized {
            get {
                return ((bool)(this["IsMainFormMaximized"]));
            }
            set {
                this["IsMainFormMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ComboBoxGoogleTimeZoneShift {
            get {
                return ((int)(this["ComboBoxGoogleTimeZoneShift"]));
            }
            set {
                this["ComboBoxGoogleTimeZoneShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ComboBoxGoogleLocationInterval {
            get {
                return ((int)(this["ComboBoxGoogleLocationInterval"]));
            }
            set {
                this["ComboBoxGoogleLocationInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int ComboBoxMapZoomLevel {
            get {
                return ((int)(this["ComboBoxMapZoomLevel"]));
            }
            set {
                this["ComboBoxMapZoomLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RenderertoolStripComboBox {
            get {
                return ((int)(this["RenderertoolStripComboBox"]));
            }
            set {
                this["RenderertoolStripComboBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseWarningWindowsAutomatically {
            get {
                return ((bool)(this["CloseWarningWindowsAutomatically"]));
            }
            set {
                this["CloseWarningWindowsAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MediaAiConfidence {
            get {
                return ((int)(this["MediaAiConfidence"]));
            }
            set {
                this["MediaAiConfidence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeKeywords {
            get {
                return ((int)(this["CellSizeKeywords"]));
            }
            set {
                this["CellSizeKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizePeoples {
            get {
                return ((int)(this["CellSizePeoples"]));
            }
            set {
                this["CellSizePeoples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeMap {
            get {
                return ((int)(this["CellSizeMap"]));
            }
            set {
                this["CellSizeMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeDates {
            get {
                return ((int)(this["CellSizeDates"]));
            }
            set {
                this["CellSizeDates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeExiftool {
            get {
                return ((int)(this["CellSizeExiftool"]));
            }
            set {
                this["CellSizeExiftool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeWarnings {
            get {
                return ((int)(this["CellSizeWarnings"]));
            }
            set {
                this["CellSizeWarnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeProperties {
            get {
                return ((int)(this["CellSizeProperties"]));
            }
            set {
                this["CellSizeProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHistortyColumns {
            get {
                return ((bool)(this["ShowHistortyColumns"]));
            }
            set {
                this["ShowHistortyColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowErrorColumns {
            get {
                return ((bool)(this["ShowErrorColumns"]));
            }
            set {
                this["ShowErrorColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CellSizeRename {
            get {
                return ((int)(this["CellSizeRename"]));
            }
            set {
                this["CellSizeRename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%Trim%%MediaFileNow_DateTime% %FileNameWithoutDateTime%%Extension%")]
        public string RenameVariable {
            get {
                return ((string)(this["RenameVariable"]));
            }
            set {
                this["RenameVariable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy_MM_dd_HH_mm_ss\r\nyyyy_MM_dd-HH_mm_ss\r\nyyyy_MM_dd HH_mm_ss\r\nyyyy_MM_dd.HH_mm_s" +
            "s\r\nyyyy_MM_ddHH_mm_ss\r\n\r\nyyyy_MM_dd_HH.mm.ss\r\nyyyy_MM_dd-HH.mm.ss\r\nyyyy_MM_dd HH" +
            ".mm.ss\r\nyyyy_MM_dd.HH.mm.ss\r\nyyyy_MM_ddHH.mm.ss\r\n\r\nyyyy_MM_dd_HH mm ss\r\nyyyy_MM_" +
            "dd-HH mm ss\r\nyyyy_MM_dd HH mm ss\r\nyyyy_MM_dd.HH mm ss\r\nyyyy_MM_ddHH mm ss\r\n\r\nyyy" +
            "y_MM_dd_HHmmss\r\nyyyy_MM_dd-HHmmss\r\nyyyy_MM_dd HHmmss\r\nyyyy_MM_dd.HHmmss\r\nyyyy_MM" +
            "_ddHHmmss\r\n\r\n\r\n\r\n\r\nyyyy-MM-dd_HH-mm-ss\r\nyyyy-MM-dd-HH-mm-ss\r\nyyyy-MM-dd HH-mm-ss" +
            "\r\nyyyy-MM-dd.HH-mm-ss\r\nyyyy-MM-dd.HH-mm-ss\r\nyyyy-MM-ddHH-mm-ss\r\n\r\nyyyy-MM-dd_HH." +
            "mm.ss\r\nyyyy-MM-dd-HH.mm.ss\r\nyyyy-MM-dd HH.mm.ss\r\nyyyy-MM-dd.HH.mm.ss\r\nyyyy-MM-dd" +
            "HH.mm.ss\r\n\r\nyyyy-MM-dd_HH mm ss\r\nyyyy-MM-dd-HH mm ss\r\nyyyy-MM-dd HH mm ss\r\nyyyy-" +
            "MM-dd.HH mm ss\r\nyyyy-MM-ddHH mm ss\r\n\r\nyyyy-MM-dd_HHmmss\r\nyyyy-MM-dd-HHmmss\r\nyyyy" +
            "-MM-dd HHmmss\r\nyyyy-MM-dd.HHmmss\r\nyyyy-MM-ddHHmmss\r\n\r\n\r\n\r\n\r\nyyyy MM dd_HH-mm-ss\r" +
            "\nyyyy MM dd-HH-mm-ss\r\nyyyy MM dd HH-mm-ss\r\nyyyy MM dd.HH-mm-ss\r\nyyyy MM ddHH-mm-" +
            "ss\r\n\r\nyyyy MM dd_HH.mm.ss\r\nyyyy MM dd-HH.mm.ss\r\nyyyy MM dd HH.mm.ss\r\nyyyy MM dd." +
            "HH.mm.ss\r\nyyyy MM ddHH.mm.ss\r\n\r\nyyyy MM dd_HH mm ss\r\nyyyy MM dd-HH mm ss\r\nyyyy M" +
            "M dd HH mm ss\r\nyyyy MM dd.HH mm ss\r\nyyyy MM ddHH mm ss\r\n\r\nyyyy MM dd_HHmmss\r\nyyy" +
            "y MM dd-HHmmss\r\nyyyy MM dd HHmmss\r\nyyyy MM dd.HHmmss\r\nyyyy MM ddHHmmss\r\n\r\n\r\n\r\n\r\n" +
            "yyyy.MM.dd_HH-mm-ss\r\nyyyy.MM.dd-HH-mm-ss\r\nyyyy.MM.dd HH-mm-ss\r\nyyyy.MM.dd.HH-mm-" +
            "ss\r\nyyyy.MM.ddHH-mm-ss\r\n\r\nyyyy.MM.dd_HH.mm.ss\r\nyyyy.MM.dd-HH.mm.ss\r\nyyyy.MM.dd H" +
            "H.mm.ss\r\nyyyy.MM.dd.HH.mm.ss\r\nyyyy.MM.ddHH.mm.ss\r\n\r\nyyyy.MM.dd_HH mm ss\r\nyyyy.MM" +
            ".dd-HH mm ss\r\nyyyy.MM.dd HH mm ss\r\nyyyy.MM.dd.HH mm ss\r\nyyyy.MM.ddHH mm ss\r\n\r\nyy" +
            "yy.MM.dd_HHmmss\r\nyyyy.MM.dd-HHmmss\r\nyyyy.MM.dd HHmmss\r\nyyyy.MM.dd.HHmmss\r\nyyyy.M" +
            "M.ddHHmmss\r\n\r\n\r\n\r\n\r\nyyyyMMdd_HH-mm-ss\r\nyyyyMMdd-HH-mm-ss\r\nyyyyMMdd HH-mm-ss\r\nyyy" +
            "yMMdd.HH-mm-ss\r\nyyyyMMddHH-mm-ss\r\n\r\nyyyyMMdd_HH.mm.ss\r\nyyyyMMdd-HH.mm.ss\r\nyyyyMM" +
            "dd HH.mm.ss\r\nyyyyMMdd.HH.mm.ss\r\nyyyyMMddHH.mm.ss\r\n\r\nyyyyMMdd_HH mm ss\r\nyyyyMMdd-" +
            "HH mm ss\r\nyyyyMMdd HH mm ss\r\nyyyyMMdd.HH mm ss\r\nyyyyMMddHH mm ss\r\n\r\nyyyyMMdd_HHm" +
            "mss\r\nyyyyMMdd-HHmmss\r\nyyyyMMdd HHmmss\r\nyyyyMMdd.HHmmss\r\nyyyyMMddHHmmss\r\n\r\n\r\n\r\n\r\n" +
            "\r\n\r\n\r\nyyyy_MM_dd_HH_mm\r\nyyyy_MM_dd-HH_mm\r\nyyyy_MM_dd HH_mm\r\nyyyy_MM_dd.HH_mm\r\nyy" +
            "yy_MM_ddHH_mm\r\n\r\nyyyy_MM_dd_HH.mm\r\nyyyy_MM_dd-HH.mm\r\nyyyy_MM_dd HH.mm\r\nyyyy_MM_d" +
            "d.HH.mm\r\nyyyy_MM_ddHH.mm\r\n\r\nyyyy_MM_dd_HH mm\r\nyyyy_MM_dd-HH mm\r\nyyyy_MM_dd HH mm" +
            "\r\nyyyy_MM_dd.HH mm\r\nyyyy_MM_ddHH mm\r\n\r\nyyyy_MM_dd_HHmm\r\nyyyy_MM_dd-HHmm\r\nyyyy_MM" +
            "_dd HHmm\r\nyyyy_MM_dd.HHmm\r\nyyyy_MM_ddHHmm\r\n\r\n\r\n\r\n\r\nyyyy-MM-dd_HH-mm\r\nyyyy-MM-dd-" +
            "HH-mm\r\nyyyy-MM-dd HH-mm\r\nyyyy-MM-dd.HH-mm\r\nyyyy-MM-dd.HH-mm\r\nyyyy-MM-ddHH-mm\r\n\r\n" +
            "yyyy-MM-dd_HH.mm\r\nyyyy-MM-dd-HH.mm\r\nyyyy-MM-dd HH.mm\r\nyyyy-MM-dd.HH.mm\r\nyyyy-MM-" +
            "ddHH.mm\r\n\r\nyyyy-MM-dd_HH mm\r\nyyyy-MM-dd-HH mm\r\nyyyy-MM-dd HH mm\r\nyyyy-MM-dd.HH m" +
            "m\r\nyyyy-MM-ddHH mm\r\n\r\nyyyy-MM-dd_HHmm\r\nyyyy-MM-dd-HHmm\r\nyyyy-MM-dd HHmm\r\nyyyy-MM" +
            "-dd.HHmm\r\nyyyy-MM-ddHHmm\r\n\r\n\r\n\r\n\r\nyyyy MM dd_HH-mm\r\nyyyy MM dd-HH-mm\r\nyyyy MM dd" +
            " HH-mm\r\nyyyy MM dd.HH-mm\r\nyyyy MM ddHH-mm\r\n\r\nyyyy MM dd_HH.mm\r\nyyyy MM dd-HH.mm\r" +
            "\nyyyy MM dd HH.mm\r\nyyyy MM dd.HH.mm\r\nyyyy MM ddHH.mm\r\n\r\nyyyy MM dd_HH mm\r\nyyyy M" +
            "M dd-HH mm\r\nyyyy MM dd HH mm\r\nyyyy MM dd.HH mm\r\nyyyy MM ddHH mm\r\n\r\nyyyy MM dd_HH" +
            "mm\r\nyyyy MM dd-HHmm\r\nyyyy MM dd HHmm\r\nyyyy MM dd.HHmm\r\nyyyy MM ddHHmm\r\n\r\n\r\n\r\n\r\ny" +
            "yyy.MM.dd_HH-mm\r\nyyyy.MM.dd-HH-mm\r\nyyyy.MM.dd HH-mm\r\nyyyy.MM.dd.HH-mm\r\nyyyy.MM.d" +
            "dHH-mm\r\n\r\nyyyy.MM.dd_HH.mm\r\nyyyy.MM.dd-HH.mm\r\nyyyy.MM.dd HH.mm\r\nyyyy.MM.dd.HH.mm" +
            "\r\nyyyy.MM.ddHH.mm\r\n\r\nyyyy.MM.dd_HH mm\r\nyyyy.MM.dd-HH mm\r\nyyyy.MM.dd HH mm\r\nyyyy." +
            "MM.dd.HH mm\r\nyyyy.MM.ddHH mm\r\n\r\nyyyy.MM.dd_HHmm\r\nyyyy.MM.dd-HHmm\r\nyyyy.MM.dd HHm" +
            "m\r\nyyyy.MM.dd.HHmm\r\nyyyy.MM.ddHHmm\r\n\r\n\r\n\r\n\r\nyyyyMMdd_HH-mm\r\nyyyyMMdd-HH-mm\r\nyyyy" +
            "MMdd HH-mm\r\nyyyyMMdd.HH-mm\r\nyyyyMMddHH-mm\r\n\r\nyyyyMMdd_HH.mm\r\nyyyyMMdd-HH.mm\r\nyyy" +
            "yMMdd HH.mm\r\nyyyyMMdd.HH.mm\r\nyyyyMMddHH.mm\r\n\r\nyyyyMMdd_HH mm\r\nyyyyMMdd-HH mm\r\nyy" +
            "yyMMdd HH mm\r\nyyyyMMdd.HH mm\r\nyyyyMMddHH mm\r\n\r\nyyyyMMdd_HHmm\r\nyyyyMMdd-HHmm\r\nyyy" +
            "yMMdd HHmm\r\nyyyyMMdd.HHmm\r\nyyyyMMddHHmm\r\n\r\n\r\n\r\nyyyy_MM_dd\r\nyyyy-MM-dd\r\nyyyy MM d" +
            "d\r\nyyyy.MM.dd\r\nyyyyMMdd\r\n\r\n")]
        public string RenameDateFormats {
            get {
                return ((string)(this["RenameDateFormats"]));
            }
            set {
                this["RenameDateFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoCorrect {
            get {
                return ((string)(this["AutoCorrect"]));
            }
            set {
                this["AutoCorrect"] = value;
            }
        }
    }
}
